CREATE TABLE IF NOT EXISTS payroll_policy (
    id BIGINT NOT NULL AUTO_INCREMENT,
    client_id BIGINT NOT NULL,
    policy_type VARCHAR(32) NOT NULL,
    policy_name VARCHAR(160) NOT NULL,
    policy_config_json TEXT NULL,
    effective_from DATE NULL,
    effective_to DATE NULL,
    active BIT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_payroll_policy_client_type_name (client_id, policy_type, policy_name),
    KEY idx_payroll_policy_client_type (client_id, policy_type, active)
);

CREATE TABLE IF NOT EXISTS employee_payroll_config (
    id BIGINT NOT NULL AUTO_INCREMENT,
    client_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    monthly_gross_salary DECIMAL(14,2) DEFAULT 0.00,
    basic DECIMAL(14,2) DEFAULT 0.00,
    hra DECIMAL(14,2) DEFAULT 0.00,
    allowances DECIMAL(14,2) DEFAULT 0.00,
    shift_reference VARCHAR(128) NULL,
    weekly_off_policy_reference VARCHAR(128) NULL,
    paid_leave_policy_reference VARCHAR(128) NULL,
    unpaid_leave_policy_reference VARCHAR(128) NULL,
    late_policy_id BIGINT NULL,
    permission_policy_id BIGINT NULL,
    overtime_rate DECIMAL(14,2) DEFAULT 0.00,
    pf_enabled BIT NOT NULL DEFAULT 0,
    pf_amount DECIMAL(14,2) DEFAULT 0.00,
    pf_percentage DECIMAL(7,2) DEFAULT 0.00,
    esi_enabled BIT NOT NULL DEFAULT 0,
    esi_amount DECIMAL(14,2) DEFAULT 0.00,
    esi_percentage DECIMAL(7,2) DEFAULT 0.00,
    professional_tax DECIMAL(14,2) DEFAULT 0.00,
    other_deductions DECIMAL(14,2) DEFAULT 0.00,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    created_by VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_employee_payroll_config_effective (client_id, employee_id, effective_from),
    KEY idx_employee_payroll_config_lookup (client_id, employee_id, effective_from, effective_to),
    KEY idx_employee_payroll_config_employee (employee_id),
    KEY idx_employee_payroll_config_late_policy (late_policy_id),
    KEY idx_employee_payroll_config_permission_policy (permission_policy_id)
);

CREATE TABLE IF NOT EXISTS payroll_daily_ledger (
    id BIGINT NOT NULL AUTO_INCREMENT,
    client_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    payroll_date DATE NOT NULL,
    attendance_record_id BIGINT NULL,
    attendance_status VARCHAR(64) NULL,
    display_status VARCHAR(64) NULL,
    count_status VARCHAR(64) NULL,
    worked_minutes INT NOT NULL DEFAULT 0,
    expected_minutes INT NOT NULL DEFAULT 0,
    paid_unit DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    lop_unit DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    late_minutes INT NOT NULL DEFAULT 0,
    early_out_minutes INT NOT NULL DEFAULT 0,
    permission_minutes INT NOT NULL DEFAULT 0,
    overtime_potential_minutes INT NOT NULL DEFAULT 0,
    overtime_approved_minutes INT NOT NULL DEFAULT 0,
    leave_type VARCHAR(64) NULL,
    payroll_status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    remarks VARCHAR(1000) NULL,
    source_classification_version VARCHAR(64) NULL,
    source_classification_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_payroll_daily_ledger_employee_date (client_id, employee_id, payroll_date),
    KEY idx_payroll_daily_ledger_client_date (client_id, payroll_date),
    KEY idx_payroll_daily_ledger_employee_date (employee_id, payroll_date),
    KEY idx_payroll_daily_ledger_attendance_record (attendance_record_id),
    KEY idx_payroll_daily_ledger_status (client_id, payroll_status)
);

CREATE TABLE IF NOT EXISTS monthly_payroll (
    id BIGINT NOT NULL AUTO_INCREMENT,
    client_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    payroll_month INT NOT NULL,
    payroll_year INT NOT NULL,
    gross_salary DECIMAL(14,2) DEFAULT 0.00,
    paid_units DECIMAL(7,2) DEFAULT 0.00,
    lop_units DECIMAL(7,2) DEFAULT 0.00,
    worked_minutes INT NOT NULL DEFAULT 0,
    expected_minutes INT NOT NULL DEFAULT 0,
    approved_ot_minutes INT NOT NULL DEFAULT 0,
    basic_pay DECIMAL(14,2) DEFAULT 0.00,
    hra_pay DECIMAL(14,2) DEFAULT 0.00,
    allowance_pay DECIMAL(14,2) DEFAULT 0.00,
    ot_amount DECIMAL(14,2) DEFAULT 0.00,
    bonus DECIMAL(14,2) DEFAULT 0.00,
    incentive DECIMAL(14,2) DEFAULT 0.00,
    arrears DECIMAL(14,2) DEFAULT 0.00,
    pf DECIMAL(14,2) DEFAULT 0.00,
    esi DECIMAL(14,2) DEFAULT 0.00,
    professional_tax DECIMAL(14,2) DEFAULT 0.00,
    lop_deduction DECIMAL(14,2) DEFAULT 0.00,
    advance_recovery DECIMAL(14,2) DEFAULT 0.00,
    other_deduction DECIMAL(14,2) DEFAULT 0.00,
    total_earnings DECIMAL(14,2) DEFAULT 0.00,
    total_deductions DECIMAL(14,2) DEFAULT 0.00,
    net_salary DECIMAL(14,2) DEFAULT 0.00,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    approved_by VARCHAR(255) NULL,
    approved_at DATETIME NULL,
    locked_by VARCHAR(255) NULL,
    locked_at DATETIME NULL,
    payslip_id VARCHAR(128) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_monthly_payroll_employee_period (client_id, employee_id, payroll_month, payroll_year),
    KEY idx_monthly_payroll_client_period (client_id, payroll_year, payroll_month),
    KEY idx_monthly_payroll_status (client_id, status),
    KEY idx_monthly_payroll_employee (employee_id)
);

CREATE TABLE IF NOT EXISTS payroll_adjustment (
    id BIGINT NOT NULL AUTO_INCREMENT,
    client_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    payroll_month INT NOT NULL,
    payroll_year INT NOT NULL,
    adjustment_type VARCHAR(48) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    reason VARCHAR(1000) NULL,
    created_by VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_payroll_adjustment_employee_period (client_id, employee_id, payroll_year, payroll_month),
    KEY idx_payroll_adjustment_client_period (client_id, payroll_year, payroll_month)
);

CREATE TABLE IF NOT EXISTS payroll_status_audit (
    id BIGINT NOT NULL AUTO_INCREMENT,
    monthly_payroll_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    from_status VARCHAR(32) NULL,
    to_status VARCHAR(32) NOT NULL,
    changed_by VARCHAR(255) NULL,
    remarks VARCHAR(1000) NULL,
    changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_payroll_status_audit_monthly (monthly_payroll_id),
    KEY idx_payroll_status_audit_client_employee (client_id, employee_id)
);
